version: "3.2"
services:
  server:
    build:
      context: ./server/
      dockerfile: dev.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./server/:/usr/app/
    depends_on:
      - db
    environment:
      - "TOKEN_AUTH_SECRET=secret"
      - "FLUTTERWAVE_API_KEY=FLWSECK_TEST-2b200882a3871d5d4cb57e349ed5fe03-X"
      - "PORT=8000"
  client:
    build:
      context: ./client/
      dockerfile: dev.Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./client/:/usr/app/
      - /usr/app/node_modules/
    environment:
      - NODE_ENV=development
  merchant-client:
    build:
      context: ./merchant-client/
      dockerfile: dev.Dockerfile
    tty: true
    ports:
      - 8080:3000
    volumes:
      - ./merchant-client/:/usr/app/
      - /usr/app/node_modules/
    environment:
      - NODE_ENV=development
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
#    command: ["postgres", "-c", "log_statement=all"]
