version: "3.2"
services:
  server:
    build:
      context: ./server/
      dockerfile: dev.Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./server/:/usr/app/
    depends_on:
      - db
  client:
    build:
      context: ./client/
      dockerfile: dev.Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./client/:/usr/app/
      - /usr/app/node_modules/
    environment:
      - NODE_ENV=development
  merchant-client:
    build:
      context: ./merchant-client/
      dockerfile: dev.Dockerfile
    tty: true
    ports:
      - 8080:3000
    volumes:
      - ./merchant-client/:/usr/app/
      - /usr/app/node_modules/
    environment:
      - NODE_ENV=development
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password